### ISSUE TITLE
大屏手机显示不全

### ISSUE THREAD

**Issue by jp1017** [githubwing/compassView#1]
![screenshot_2016-02-16-15-44-02_com wingsofts thre](https://cloud.githubusercontent.com/assets/7868514/13070050/422fd628-d4c4-11e5-99f4-70a6dfeef8a7.png)

红米note3，显示如上，不忍直视

另外，后面还会添加方向传感器实现指南针吗？

**Comment by githubwing** [comment]
这个是个demo来的。。 你可以根据自己的需求去定制~~

**Comment by jp1017** [comment]
3ks，good job.

**Comment by githubwing** [comment]
@jp1017  http://blog.csdn.net/wingichoy/article/details/50590051 这里有教程 你可以自己改一下大小 然后重新测量 动态计算大小
